server:
  port: 8075
  corst: ["*"]
openWeather:
  host: "https://api.openweathermap.org/"
  currentWeatherEndpoint: "data/2.5/weather?lat=%s&lon=%s&appid=%s&units=%s"
  units: "metric"
  apiKey: "YOUR_API_KEY_HERE"
  timeout: 5

